'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.3038.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
 System.SerializableAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True), _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)> _
Partial Public Class views

    Private viewField() As viewsView

    Private nameField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("view")> _
    Public Property view() As viewsView()
        Get
            Return Me.viewField
        End Get
        Set(value As viewsView())
            Me.viewField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set(value As String)
            Me.nameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class viewsView

    Private titleField As String

    Private sqlField As String

    Private xAxisLabelField As String

    Private yAxisLabelField As String

    Private y2AxisLabelField As String

    Private y3AxisLabelField As String

    Private y4AxisLabelField As String

    Private y5AxisLabelField As String

    Private parametersField() As viewsViewParameter

    Private itemCapField As Byte

    Private fieldsField() As viewsViewField

    Private relationshipField As viewsViewRelationship

    Private idField As Byte

    Private defaultSortField As String

    Private showChartField As String

    '''<remarks/>
    Public Property title() As String
        Get
            Return Me.titleField
        End Get
        Set(value As String)
            Me.titleField = value
            RaisePropertyChanged("title")
        End Set
    End Property

    '''<remarks/>
    Public Property sql() As String
        Get
            Return Me.sqlField
        End Get
        Set(value As String)
            Me.sqlField = value
        End Set
    End Property

    '''<remarks/>
    Public Property xAxisLabel() As String
        Get
            Return Me.xAxisLabelField
        End Get
        Set(value As String)
            Me.xAxisLabelField = value
        End Set
    End Property

    '''<remarks/>
    Public Property yAxisLabel() As String
        Get
            Return Me.yAxisLabelField
        End Get
        Set(value As String)
            Me.yAxisLabelField = value
        End Set
    End Property

    '''<remarks/>
    Public Property y2AxisLabel() As String
        Get
            Return Me.y2AxisLabelField
        End Get
        Set(value As String)
            Me.y2AxisLabelField = value
        End Set
    End Property

    '''<remarks/>
    Public Property y3AxisLabel() As String
        Get
            Return Me.y3AxisLabelField
        End Get
        Set(value As String)
            Me.y3AxisLabelField = value
        End Set
    End Property

    '''<remarks/>
    Public Property y4AxisLabel() As String
        Get
            Return Me.y4AxisLabelField
        End Get
        Set(value As String)
            Me.y4AxisLabelField = value
        End Set
    End Property

    '''<remarks/>
    Public Property y5AxisLabel() As String
        Get
            Return Me.y5AxisLabelField
        End Get
        Set(value As String)
            Me.y5AxisLabelField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("parameter", IsNullable:=False)> _
    Public Property parameters() As viewsViewParameter()
        Get
            Return Me.parametersField
        End Get
        Set(value As viewsViewParameter())
            Me.parametersField = value
            RaisePropertyChanged("parameters")
        End Set
    End Property

    '''<remarks/>
    Public Property itemCap() As Byte
        Get
            Return Me.itemCapField
        End Get
        Set(value As Byte)
            Me.itemCapField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("field", IsNullable:=False)> _
    Public Property fields() As viewsViewField()
        Get
            Return Me.fieldsField
        End Get
        Set(value As viewsViewField())
            Me.fieldsField = value
        End Set
    End Property

    '''<remarks/>
    Public Property relationship() As viewsViewRelationship
        Get
            Return Me.relationshipField
        End Get
        Set(value As viewsViewRelationship)
            Me.relationshipField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property id() As Byte
        Get
            Return Me.idField
        End Get
        Set(value As Byte)
            Me.idField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property defaultSort() As String
        Get
            Return Me.defaultSortField
        End Get
        Set(value As String)
            Me.defaultSortField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property showChart() As String
        Get
            Return Me.showChartField
        End Get
        Set(value As String)
            Me.showChartField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class viewsViewParameter

    Private nameField As String

    Private requiredField As Boolean

    Private columnNameField As String

    Private operatorField As String

    Private typeField As String

    Private defaultValueField As String

    '''<remarks/>
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set(value As String)
            Me.nameField = value
        End Set
    End Property

    '''<remarks/>
    Public Property required() As Boolean
        Get
            Return Me.requiredField
        End Get
        Set(value As Boolean)
            Me.requiredField = value
        End Set
    End Property

    '''<remarks/>
    Public Property columnName() As String
        Get
            Return Me.columnNameField
        End Get
        Set(value As String)
            Me.columnNameField = value
        End Set
    End Property

    '''<remarks/>
    Public Property [operator]() As String
        Get
            Return Me.operatorField
        End Get
        Set(value As String)
            Me.operatorField = value
        End Set
    End Property

    '''<remarks/>
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set(value As String)
            Me.typeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property defaultValue() As String
        Get
            Return Me.defaultValueField
        End Get
        Set(value As String)
            Me.defaultValueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class viewsViewField

    Private nameField As String

    Private formattingField As String

    Private mathExpressionField As String

    Private labelField As String

    Private calcTotalsField As Boolean

    Private axisYField As Boolean

    Private axisY2Field As Boolean

    Private axisY3Field As Boolean

    Private axisY4Field As Boolean

    Private axisY5Field As Boolean

    Private sortOrderField As String

    Private valueFieldField As Boolean

    Private displayNameField As String

    Private visibleField As Boolean

    '''<remarks/>
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set(value As String)
            Me.nameField = value
            RaisePropertyChanged("name")
        End Set
    End Property

    '''<remarks/>
    Public Property formatting() As String
        Get
            Return Me.formattingField
        End Get
        Set(value As String)
            Me.formattingField = value
        End Set
    End Property

    '''<remarks/>
    Public Property mathExpression() As String
        Get
            Return Me.mathExpressionField
        End Get
        Set(value As String)
            Me.mathExpressionField = value
        End Set
    End Property

    '''<remarks/>
    Public Property label() As String
        Get
            Return Me.labelField
        End Get
        Set(value As String)
            Me.labelField = value
        End Set
    End Property

    '''<remarks/>
    <System.ComponentModel.DefaultValue(True)>
    Public Property calcTotals() As Boolean
        Get
            Return Me.calcTotalsField
        End Get
        Set(value As Boolean)
            Me.calcTotalsField = value
        End Set
    End Property

    '''<remarks/>
    Public Property axisY() As Boolean
        Get
            Return Me.axisYField
        End Get
        Set(value As Boolean)
            Me.axisYField = value
        End Set
    End Property

    '''<remarks/>
    Public Property axisY2() As Boolean
        Get
            Return Me.axisY2Field
        End Get
        Set(value As Boolean)
            Me.axisY2Field = value
        End Set
    End Property

    '''<remarks/>
    Public Property axisY3() As Boolean
        Get
            Return Me.axisY3Field
        End Get
        Set(value As Boolean)
            Me.axisY3Field = value
        End Set
    End Property

    '''<remarks/>
    Public Property axisY4() As Boolean
        Get
            Return Me.axisY4Field
        End Get
        Set(value As Boolean)
            Me.axisY4Field = value
        End Set
    End Property

    '''<remarks/>
    Public Property axisY5() As Boolean
        Get
            Return Me.axisY5Field
        End Get
        Set(value As Boolean)
            Me.axisY5Field = value
        End Set
    End Property

    '''<remarks/>
    Public Property sortOrder() As String
        Get
            Return Me.sortOrderField
        End Get
        Set(value As String)
            Me.sortOrderField = value
        End Set
    End Property

    '''<remarks/>
    Public Property valueField() As Boolean
        Get
            Return Me.valueFieldField
        End Get
        Set(value As Boolean)
            Me.valueFieldField = value
        End Set
    End Property

    '''<remarks/>
    Public Property displayName() As String
        Get
            Return Me.displayNameField
        End Get
        Set(value As String)
            Me.displayNameField = value
            Me.label = value
        End Set
    End Property

    '''<remarks/>
    Public Property visible() As Boolean
        Get
            Return Me.visibleField
        End Get
        Set(value As Boolean)
            Me.visibleField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class viewsViewRelationship

    Private fieldNameField As String

    Private viewIdField As String

    '''<remarks/>
    Public Property fieldName() As String
        Get
            Return Me.fieldNameField
        End Get
        Set(value As String)
            Me.fieldNameField = value
        End Set
    End Property

    '''<remarks/>
    Public Property viewId() As String
        Get
            Return Me.viewIdField
        End Get
        Set(value As String)
            Me.viewIdField = value
        End Set
    End Property
End Class
